version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo **** Npm Install ****
      - cd $CODEBUILD_SRC_DIR/src/ApiLambda
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - export BUCKET=$S3Bucket
      - sam package --template-file template.json --s3-bucket $BUCKET --output-template-file outputtemplate.yml
  post_build:
    commands:
      - ls
      - pwd
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - outputtemplate.yml
    - dev-config.json
    - test-config.json
    - prod-config.json
